import { Heebo } from 'next/font/google'
import '../styles/globals.css'
const heebo = Heebo({ subsets: ['latin'] })

export const metadata = {
	title: 'AmexWebDev',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body className={heebo.className}>{children}</body>
		</html>
	)
}
